networks:
  ihsan-solusi:
     driver: bridge

services:
  account-service:
    build: .
    container_name: account-service
    command: ["/app/main", "-host=${APP_HOST}", "-port=${APP_PORT}"]
    ports:
      - "${APP_PORT}:${APP_PORT}"
    network: ihsan-solusi
    environment:
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_PORT: "${DB_PORT}"

  db:
    image: postgres:17.4
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    network: ihsan-solusi